# Generated by Django 4.2.1 on 2023-05-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganapp', '0004_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
